// 다중 catch

package sec01.exam03;

public class TryCatchFinallyRuntimeEx {
	// 다중 catch
	public static void main(String[] args) {
		String data1 = null;
		String data2 = null;
		try {
			data1 = args[0];
			data2 = args[1];
			int value1 = Integer.parseInt(data1);
			int value2 = Integer.parseInt(data2);
			int result = value1 + value2;
			System.out.println(value1 + "+" + value2 + "=" + result);
		} catch (ArrayIndexOutOfBoundsException e) {// <= 배열 예외 생겼을때 처리
			System.out.println("실행 매개값의 수가 부족합니다.");
		} catch (NumberFormatException e) {// <= 문자열로 되어 있는 데이터를 숫자로 변경할때 예외 처리
			e.printStackTrace();
			System.out.println("숫자로 변화할 수 없습니다.");
		}finally {// <= 항상 실행
			System.out.println("다시 실행 하세요.");
		}
	}

}
